en={
    'key_general_error': 'Format of "$KEY$" is illegal',
    'missing_required_key': 'Missing required key "$KEY$"',
    'none_value': 'Value of "$KEY$" can not be none',
    'not_int': 'Value of "$KEY$" must be an integer',
    'not_str': 'Value of "$KEY$" must be a string',
    'not_float': 'Value of "$KEY$" must be a float',
    'not_bool': 'Value of "$KEY$" must be a boolean',
    'not_number': 'Value of "$KEY$" must be a number',
    'not_array': 'Value of "$KEY$" must be an array',
    'no_type_match': 'Type of "$KEY$" is illegal',
    'max_length': 'Max length of "$KEY$" is $LENGTH$',
    'max_limit': '"$KEY$" should be no more than $MAX$',
    'min_limit': '"$KEY$" should be no less than $MIN$',
}

zh={
    'key_general_error': '"$KEY$"格式错误',
    'missing_required_key': '缺少"$KEY$"',
    'none_value': '"$KEY$"的值不能为空',
    'not_int': '"$KEY$"必须是一个整数',
    'not_str': '"$KEY$"必须是一个字符串',
    'not_float': '"$KEY$"必须是一个浮点数',
    'not_bool': '"$KEY$"必须是一个布尔值',
    'not_number': '"$KEY$"必须是一个数字',
    'not_array': '"$KEY$"必须是一个数组',
    'no_type_match': '"$KEY$"类型错误',
    'max_length': '"$KEY$"的最大长度为$LENGTH$',
    'max_limit': '"$KEY$"最大为$MAX$',
    'min_limit': '"$KEY$"最小为$MIN$',
}